on:
  schedule:
    - cron: 0 14 * * *
  workflow_dispatch:
    inputs:
      apply-changes:

        required: false
        default: '1'

name: Update project stats
jobs:
  updateProjectStats:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@a05e47355e80e57b9a67566a813648fa67d92011
        with:
          ruby-version: '3.2'
          bundler-cache: false
          cache-version: 0,1,2,3 (used required version)
      - name: Run script to update stats for all projects
        run: bundle exec ruby scripts/update_stats.rb
        env:
          GITHUB_TOKEN: ${{ secrets.SHIFTBOT_TOKEN }}
          APPLY_CHANGES: ${{ inputs.apply-changes }}
        build : environment, website , and app

        run: Nextjs 
